### ISSUE TITLE
usb randomly not working 

### ISSUE THREAD

**Issue by koli998** [niypoo/gigabyte-b660m-aorus-pro-ax-ddr4-monterey-hackintosh#1]
What kind of freezing randomly Issue are you encountering?

There is a problem that bothers me, that is, the keyboard and mouse will suddenly not working. At this time, all usbs are not working, and it is useless to unplug and plug again. But the computer is still working. This happens about once a day.

**Comment by niypoo** [comment]
No The issue That was happened with me is " freezing keyword and mouse and even system" everything ware freezing.

best step you have to make that "reset the bios to default and test" for reducing the cases.

**Comment by koli998** [comment]
Thanks for your reminder. I have reset the bios before following the settings.

**Comment by MoZhouqi** [comment]
I still has the problem, which wireless card do you use?

**Comment by koli998** [comment]
I still have this problem, what wireless card are you using?
